### ISSUE TITLE
Error on new_branch command

### ISSUE THREAD

**Issue by user2684** [egeoffrey/egeoffrey-cli#11]
**Describe the bug**
Error when creating a new branch and the branch does not already exists

```
$ egeoffrey-cli new_branch development
Switching to branch development
error: unable to delete 'development': remote ref does not exist
error: failed to push some refs to 'https://github.com/egeoffrey/egeoffrey-gui.git'
Traceback (most recent call last):
  File "/usr/local/bin/egeoffrey-cli", line 1266, in <module>
    if not OFFLINE: run_git(["push", "origin", "--delete", branch])
  File "/usr/local/bin/egeoffrey-cli", line 220, in run_git
    return subprocess.check_output(["git", "-C", directory] + args)
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', '-C', 'packages/egeoffrey-gui', 'push', 'origin', '--delete', 'development']' returned non-zero exit status 1
```

**Comment by user2684** [comment]
Fixed by fetching and ensuring the remote branch is there before deleting it
